# Generated by Django 4.0.6 on 2022-08-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='img',
            field=models.FileField(upload_to='city/', verbose_name='Logo'),
        ),
    ]
